export default Icons = {
  //SETTINGS: require('../img/settings.png'),
  USERHOME: require('../img/feed.png'),
  USERHOMEBLUE: require('../img/prof.png'),
  HOMES: require('../img/stroke-1.png'),
  FAVORITE: require('../img/heart.png'),
  USERPROFILE: require('../img/fill-1.png'),
  SETTINGS: require('../img/settings.png'),
  DOWNLOAD: require('../img/download.png'),
  HEART: require('../img/heart.png'),
  HEARTN: require('../img/heartn.png'),
  HEARTNB: require('../img/heartnb.png'),
  MINDSELF: require('../img/MindSelf.png'),
  TICK: require('../img/tick.png'),
  RING: require('../img/ring.png'),
  BACK: require('../img/back.png'),
  LEFT: require('../img/left.png'),
  RIGHT: require('../img/right.png'),
  INF: require('../img/inf.png'),
  CHECK: require('../img/check.png'),
  CHECKSUB: require('../img/checksub.png'),
  GREEN: require('../img/image-green.png'),
  PAGES: require('../img/pages.png'),
  TELEGRAM: require('../img/telegram.png'),
  VIBER: require('../img/viber.png'),
  MESSENGER: require('../img/Messenger.png'),
  WHATSAPP: require('../img/WhatsApp.png'),
  SIGNUP: require('../img/group.png'),
  F: require('../img/f.png'),
  DOWNLOADLEAVES: require('../img/downloadleaves.png'),
  DOWNLOADHEART: require('../img/downloadheart.png'),


//  RING2: require('../static/images/ring.png')

}
